require "kd.options"
require "kd.keymaps"
require "kd.plugins"
require "kd.colorscheme"
-- require "kd.completion"
-- require "kd.lsp"
-- require "kd.null-ls"
require "kd.telescope"
-- require "kd.treesitter"
-- require "kd.indentline"
-- require "kd.autopairs"
-- require "kd.comment"
-- require "kd.gitsigns"
require "kd.nvim-tree"
-- require "kd.bufferline"
-- require "kd.lualine"
require "kd.toggleterm"
require "kd.project"
require "kd.impatient"
require "kd.alpha"
require "kd.whichkey"
-- require "kd.neoscroll"
-- require "kd.colorizer"

